name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: | 
          source setup.sh
        shell: bash

      - name: Build
        run: | 
          source build.sh
        shell: bash

      - name: Test
        run: |
          source test.sh
        shell: bash
